micronaut:
  application:
    name: lojaService
  server:
    port: 8083

kafka:
  bootstap:
    servers: localhost:9092

consul:
  client:
    registration:
      enabled: true
    default-zone: "localhost:8500"