micronaut:
  application:
    name: veiculoService
  server:
    port: -1
datasources:
  default:
    url: jdbc:postgresql://127.0.0.1:5432/dbveiculo
    driverClassName: org.postgresql.Driver
    username: ${USER_NAME}
    password: ${PASSWORD}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - 'br.com.rafaelsplima.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

consul:
  client:
    registration:
      enabled: true
    default-zone: "localhost:8500"